# Generated by Django 5.2.4 on 2025-08-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_assigned_to_project_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'InProgress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=15),
        ),
    ]
